name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"


jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}
#           COMMIT_BY_ME: "True"
#           COMMIT_USERNAME: "MZzzNn"
#           COMMIT_EMAIL: "mazenn770@gmail.com"
#           SECTION_NAME: "waka-simple"
#           BLOCKS: "⣀⣄⣤⣦⣶⣷⣿"
#           TIME_RANGE: all_time
          SHOW_TIME: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_TITLE: "True"
          SHOW_OS: "True"
          SHOW_PROJECTS: "True"
          SHOW_UPDATED_DATE: "True"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LANGUAGE_PER_REPO: "False"
          SHOW_LINES_OF_CODE: "True"
          SHOW_COMMIT: "True"
          SHOW_LOC_CHART: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_SHORT_INFO: "True"
